### PR TITLE
Bump polkadot and pendulum-chain dependency versions

### PR DESCRIPTION
**Pull request by ebma**
Related to https://github.com/pendulum-chain/tasks/issues/402

### CODE REVIEW

**Comment by ebma** [comment]
I tried resolving all dependency conflicts but unfortunately it's not possible. The problem is that `@material-ui/core` requires  a react version 16 or 17 but `@talismn/connect/components` and `@rainbow-me/rainbowkit` require react 18. See the following output when running yarn install. 

```
✗ yarn
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @material-ui/core@npm:4.12.4, @emotion/hash@npm:0.8.0, @material-ui/styles@npm:4.11.5, @material-ui/system@npm:4.12.2, @material-ui/types@npm:5.1.0, @material-ui/utils@npm:4.11.3, css-vendor@npm:2.0.8, csstype@npm:2.6.21, hyphenate-style-name@npm:1.1.0, is-in-browser@npm:1.1.3, jss-plugin-camel-case@npm:10.10.0, and 9 more.
➤ YN0085: │ - @material-ui/core@npm:5.0.0-beta.5, @material-ui/private-theming@npm:5.0.0-beta.5, @material-ui/styled-engine@npm:5.0.0-beta.5, @material-ui/system@npm:5.0.0-beta.5, @material-ui/types@npm:6.0.2, @material-ui/unstyled@npm:5.0.0-alpha.44, @material-ui/utils@npm:5.0.0-beta.5, @types/react-is@npm:17.0.7
➤ YN0000: └ Completed in 0s 821ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ @types/react is listed by your project with version 17.0.83, which doesn't satisfy what @talismn/connect-components (pca977) and other dependencies request (^18.2.31).
➤ YN0060: │ react is listed by your project with version 17.1.2, which doesn't satisfy what @rainbow-me/rainbowkit (p3d9f3) and other dependencies request (^18.2.0).
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 20 packages were added to the project, and 8 were removed (- 343.12 KiB).
➤ YN0000: └ Completed in 0s 265ms
➤ YN0000: ┌ Link step
➤ YN0008: │ vortex@workspace:. must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 1s 341ms
➤ YN0000: · Done with warnings in 2s 582ms

```

I added aliases for the `react` and `react-dom` dependencies similar to what is described [here](https://preactjs.com/guide/v10/getting-started#aliasing-in-node). This gets rid of lots of warnings about dependencies not able to find the either of them.

**Comment by gianfra-t** [comment]
Yeah seems that `material-ui/core` has been [deprecated](https://www.npmjs.com/package/@material-ui/core), and people suggest to install the new [version](https://mui.com/material-ui/getting-started/installation/). Probably too much effort right?

**Comment by ebma** [comment]
Ah thanks for pointing it out @gianfra-t! We don't even use `material-ui/core` anymore, so we can remove it without any effort. 
However, already [this](https://github.com/pendulum-chain/vortex/pull/178/commits/a95e49475f368f687c079358331a4570a7208b82) commit introduced changes that broke the lint check. I need to look into the specifics but currently we have new 51 errors. Most of them are with our image icon components in `src/assets` so maybe that's an easy fix.

**Comment by gianfra-t** [comment]
Wow 51 lint errors. Well maybe we can start solving some subset of them on each PR we open so that it's not such a huge load for you on this one.

**Comment by ebma** [comment]
I went back through the commits one by one and honestly, I'm not sure why the linting failed. When I readded the dependencies step by step and always doing a `yarn && yarn lints:ts`, it didn't break at all. I assume that the `yarn.lock` file was just broken somehow. Even changing between yarn 4.0.2 and 4.5.0 didn't make the difference as far as I can tell, I just changed it to that version to make it consistent with the other repositories.

I also had to change the Github action to enable corepack so that it's installed correctly.

**Review by TorstenStueber — APPROVED** [review]
I tested locally and everything works!

**Pull request merged**
