### PR TITLE
Increase Credibility

### PR DESCRIPTION
**Pull request by Sharqiewicz**
- [x] Add powered by SatoshiPay
- [x] Add footer similar to LP

Closes https://github.com/pendulum-chain/tasks/issues/435

### CODE REVIEW

**Comment by Sharqiewicz** [comment]
@pendulum-chain/devs Ready for revies ✅

**Review by gianfra-t — APPROVED** [review]
I hope the link to Github can convince some people 👍.

Wanna tag product for a review also of the UI?

**Comment by ebma** [comment]
I think we should reduce the bottom margin of the 'powered by' message in the form. Also, the app is a little scrollable for me. It would be better if it fits on the whole 100vh of space. I'm not sure if we need to have 'Powered by SatoshiPay' twice on the screen, although technically that's how it was specified in https://github.com/pendulum-chain/tasks/issues/435. @pendulum-chain/product is this intended?

image


@Sharqiewicz please don't forget to link to the relevant ticket in the description of your PRs. Even if it's a task ticket. I added that link now.

**Comment by ebma** [comment]
Maybe we should adjust the left margin on mobile a bit and make it align with the swap form.

**Review by ebma — APPROVED** [review]
Let's go 👌

**Pull request merged**
