### PR TITLE
Ready: Enable USDT (Polygon)

### PR DESCRIPTION
**Pull request by Sharqiewicz**
🦈 🟢 PR 
---

- [x] Add USDT to the dropdown.
- [x] Add USDT Polygon to the dropdown.
- [x] Add USDT to tokenConfig to swap to USDC.axl

Closes: #263 and #262 

RainbowKit changes are included in: #276

### CODE REVIEW

**Review by ebma — APPROVED** [review]
Looks good to me, nice job 👍

**Comment by Sharqiewicz** [comment]
Thanks @ebma ❤️ 

@pendulum-chain/product Could you please test the USDT offramp?

**Comment by TorstenStueber** [comment]
Code looks good. However, we would need to add usdt to the signer service quote endpoints, otherwise the quote box doesn't work and the endpoints return 404.

These endpoints now also need to support usdt. @ebma Are you aware of whether the three providers have extra quotes for usdt (different to usdc)?

**Comment by vadaynujra** [comment]
@Sharqiewicz tested the USDT off-ramp successfully 
image

**Comment by ebma** [comment]
I checked and it seems like they do. I added the respective changes.

**Review by gianfra-t — APPROVED** [review]
Looks good 👍!

**Review by TorstenStueber — APPROVED** [review]
I tested the signer service endpoints locally, all good!

**Comment by Sharqiewicz** [comment]
thanks @ebma

**Pull request merged**
