### PR TITLE
unify button styles

### PR DESCRIPTION
**Pull request by Sharqiewicz**
PR 🦈🟢
---
Update the button styles as per design
Design -> https://www.figma.com/design/cOx99YQtxf8LLdlhZjvkoC/Vortex?node-id=1-6&t=KhKDqxQXRB5bnNju-4

Context
Currently the button designs are unclear and turn grey when hovered, This ticket is to fix all the buttons on Vortex UI

Requirement
Update all button styling on the Vortex UI
On hovered the button should turn white and border should be highlighted as shown in the design

Closes: #189

### CODE REVIEW

**Review by ebma — COMMENTED** [review]
Looks good in general but I think there are some things missing. What I noticed:

Expected (in the design)
image

Actual
image

For onclick: 
Expected 
image

Actual (same as hover)
image

**Comment by TorstenStueber** [comment]
Agree with @ebma. For me it was not clear how to interpret the designs and I first thought that the third button in each group means "disabled". But on a closer look, it seems like @ebma's interpretation is correct.

**Comment by Sharqiewicz** [comment]
@ebma @TorstenStueber @prayagd 

Primary
---

Default:
default
Disabled:
disabled
Hover:
hover
Focus:
focus
Active:
active

Secondary
---
Default:
default pink
Hover:
hover pink

**Review by TorstenStueber — COMMENTED** [review]
👍 Looks great. Can confirm that it looks like on the design you provided.

**Review by ebma — APPROVED** [review]

**Review by prayagd — APPROVED** [review]
LGTM, as per the designs

**Pull request merged**
